import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const avenueMono = localFont({
  src: "../public/fonts/AvenueMono-Regular.otf",
  variable: "--font-avenue-mono",
});

export const metadata: Metadata = {
  title: "Adrian Ordonio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${avenueMono.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
